### ISSUE TITLE
Can't edit editable areas of posts/pages when double clicked to select

### ISSUE THREAD

**Issue by doughnet** [Postleaf/postleaf#23] opened 2016-07-31 05:36 UTC
Thanks for using Postleaf! 💙💚

This issue tracker is ONLY for bug reports. If you need help with something or would like to request a feature, please ask on https://community.postleaf.org/ instead.

---

### Issue Summary

At the admin page for section with list of posts/pages you can click on a page and edit it by clicking the pencil **OR** double clicking on it.  If you double click on it _sometimes_ it does not allow for editing the inline text content.  

### Steps to Reproduce

Tell us how to replicate the problem.

1. Login as admin/author
2. Go to the Post page
3. Double click on a post or page to open it (do not click once and click on the edit/pencil icon)
4. Try to type in the editable areas. Half the time it does not allow for editting

### Additional info

- Postleaf version: version beta 1,2 & 3
- PHP version: 5.6
- Affected browsers: firefox & chrome
- Operating system: all?

Provide any additional information that may be relevant to the bug here.

**Comment by claviska** [comment] 2016-07-31 05:43
Thanks, are you seeing any errors in the JS console when this happens?

**Comment by doughnet** [comment] 2016-07-31 06:18
Nothing stands out.  Could it be something to do with Cloudflare possible?

Image of js console below:
[http://imgur.com/a/ucPEc](url)

**Comment by doughnet** [comment] 2016-07-31 06:28
I think I figured out the issue.

Issue replicated:

1. Login to your site www.domain.com/postleaf/admin  (or with your correct path)
2. Then click on a page/post, this will allow editting.
3. Then in your URL remove the www. and just have domain.com/postleaf/admin/... and refresh the same page you were editting.
4.  For me, it seems every time it will not allow me to edit the page at all or click buttons.

_It seems that it will only allow editing with the exact domain path used to login and if not it's causing authentication issues possibly?_

**Comment by claviska** [comment] 2016-07-31 15:20
The auth cookie is only set on the current domain/subdomain, which I think is appropriate. It's generally a best practice to redirect a naked domain to www or vice versa.

It _is_ possible to set the cookie for the naked domain and all subdomains, but due to the way Postleaf auto-detects the hostname it's not quite as easy as it sounds, and I'd prefer to wait to see if this is an edge case or a more common problem.

**Comment by doughnet** [comment] 2016-07-31 15:34
Were you able to recreate this?

**Comment by claviska** [comment] 2016-07-31 15:44
No, when I switch from www ==> non-www it redirects to the login page because I'm not authenticated, which is the expected behavior.

If you clear your cookies for both www and non-www and stay on the same domain the whole time, I'm sure it works correctly.

**Comment by claviska** [comment] 2016-08-02 03:50
Closing this because of our discussion on the community site. I believe this is an issue with CloudFlare, not Postleaf.

**Closed by claviska** 2016-08-02 03:50 UTC
