### ISSUE TITLE
On page pl-toolbar not visible on desktop browsers

### ISSUE THREAD

**Issue by doughnet** [Postleaf/postleaf#20] opened 2016-07-30 20:40 UTC
Thanks for using Postleaf! 💙💚

This issue tracker is ONLY for bug reports. If you need help with something or would like to request a feature, please ask on https://community.postleaf.org/ instead.

---

### Issue Summary

Once logged in and viewing a live page the pl-toolbar is only blank.  See image for example [LINK](http://imgur.com/a/ISYFB).  The area it should be is visible but the icons are not visible on desktop.  Tried on Firefox & Chrome.  On mobile devices it shows up fine.

### Steps to Reproduce

Tell us how to replicate the problem.

1. Login as admin
2. View a live page
3. Bottom right corner has overlay for pl-toolbar icons/buttons (or should)

### Additional info

- Postleaf version: 1.00 beta
- PHP version: 5.6
- Affected browsers: Chrome & Firefox
- Operating system: Windows 8.1

Provide any additional information that may be relevant to the bug here.

**Comment by claviska** [comment] 2016-07-30 21:08
This affected Firefox and IE. Should be fixed in the latest patch release. To update, just swap out the source folder with the new one (available from www.postleaf.org/download).

**Comment by claviska** [comment] 2016-07-30 21:10
Duplicate of #16

**Closed by claviska** 2016-07-30 21:10 UTC
Labels: bug, duplicate
